# Generated by Django 3.2.1 on 2021-07-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projectpost',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(default='Heading', max_length=60)),
                ('project_desc', models.TextField(default='', max_length=1000)),
                ('git_link', models.CharField(default='', max_length=500)),
                ('project_link', models.CharField(default='', max_length=500)),
                ('thumbnail', models.ImageField(default='', upload_to='media/images')),
            ],
        ),
    ]
