# Generated by Django 3.2.1 on 2021-07-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_projectpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpost',
            name='git_link',
            field=models.CharField(default='#', max_length=500),
        ),
        migrations.AlterField(
            model_name='projectpost',
            name='project_desc',
            field=models.TextField(default='project description', max_length=1000),
        ),
        migrations.AlterField(
            model_name='projectpost',
            name='project_link',
            field=models.CharField(default='#', max_length=500),
        ),
        migrations.AlterField(
            model_name='projectpost',
            name='thumbnail',
            field=models.ImageField(default='media/images/img_1.jpg', upload_to='media/images'),
        ),
    ]
